import streamlit as st
import kagglehub
import pandas as pd
import os
import numpy as np
from sklearn.linear_model import LinearRegression

# Constants
KAGGLE_DATASET = "igormerlinicomposer/f1-aerodynamic-stability-and-porpoising-150k-samp"
FEATURE_COLUMN = "speed_kmh"
TARGET_COLUMN = "downforce_n"
WING_ANGLE = "wing_angle_deg"
CSV_TABLE = "actaruslab_f1_telemetry_2026.csv"

st.title("Model explanation")

if "stage" not in st.session_state:
    st.session_state.stage = 1
if "finished" not in st.session_state:
    st.session_state.finished = False
if "data" not in st.session_state:
    st.session_state.data = None
if "x" not in st.session_state:
    st.session_state.x = None
if "y" not in st.session_state:
    st.session_state.y = None
if "bl_loss" not in st.session_state:
    st.session_state.bl_loss = None

if st.session_state.stage == 1:
    st.header("Dataset")
    st.write(
        "The first step in creating a Linear Regression model is choosing a dataset "
        "that the model will learn.\n\nIn this case, I chose the following dataset: \""
        + KAGGLE_DATASET + "\" which provides information about the aerodynamics of F1 cars."
    )

    if st.button("Download dataset"):
        with st.spinner("Downloading F1 aerodynamics dataset", show_time=True):
            path = kagglehub.dataset_download(KAGGLE_DATASET)
            csv_path = os.path.join(path, CSV_TABLE)
            st.session_state.data = pd.read_csv(csv_path)
        st.session_state.finished = True

    if st.session_state.finished:
        st.dataframe(st.session_state.data.head(10))
        st.success("The dataset was downloaded successfully")
        st.info("The provided table displays the first 10 rows of the dataset")

        if st.button("Continue"):
            st.session_state.stage = 2
            st.rerun()

elif st.session_state.stage == 2:
    st.header("x and y")
    st.write(
        "The next step is choosing the parameter to predict (y) as a function of "
        "another parameter (x).\n\nIn my case, I chose to predict the downforce that "
        "will be generated by the wind around the car (y) as a function of the speed "
        "in which it is moving (x)."
    )

    data = st.session_state.data
    x = data.loc[data[WING_ANGLE].between(5, 10), FEATURE_COLUMN].to_numpy()
    y = data.loc[data[WING_ANGLE].between(5, 10), TARGET_COLUMN].to_numpy()
    df = pd.DataFrame({
        FEATURE_COLUMN: x[:10],
        TARGET_COLUMN: y[:10],
    })
    st.dataframe(df)
    st.success("Dataset was successfully divided to x and y.")
    st.info(
        "In my case the downforce is influenced by multiple parameters (mainly the "
        "speed and the angle of the wing).\n\nFor this reason, I have limited the "
        "downforce data to include only the lines in which the wing angle is "
        "relatively similar. By doing so, I made the speed the main factor that "
        "controls the amount of downforce.\n\nThe wing angle that I have based it "
        "on is 5 - 10 degrees."
    )

    st.session_state.x = x
    st.session_state.y = y

    con, prev = st.columns(2)

    if con.button("Continue"):
        st.session_state.stage = 3
        st.rerun()
    if prev.button("Previous"):
        st.session_state.stage = 1
        st.rerun()

elif st.session_state.stage == 3:
    st.header("Reviewing the values")
    x = st.session_state.x
    y = st.session_state.y

    st.warning(
        "**Reminder**\n\n"
        "y - The parameter we want to predict\n\n"
        "x - The parameter that influences y"
    )
    st.write(
        "After deciding and seperating the data to x and y, we want to make sure that there is a Linear connection between them.\n\n"
        "Here is the scatter chart for the dataset that I chose to use: "
    )

    df = pd.DataFrame({
        FEATURE_COLUMN: x[:1000],
        TARGET_COLUMN: y[:1000],
    })

    st.scatter_chart(df, x=FEATURE_COLUMN, y=TARGET_COLUMN)

    st.info(
        "Note that there is a pretty Linear relation between x and y.\n\n"
        "This chart displays only 1,000/24,880 rows of the dataset, in order to make the experience smoother."
    )

    con, prev = st.columns(2)

    if con.button("Continue"):
        st.session_state.stage = 4
        st.rerun()
    if prev.button("Previous"):
        st.session_state.stage = 2
        st.rerun()

elif st.session_state.stage == 4:
    st.header("Baseline Prediction")
    x = st.session_state.x
    y = st.session_state.y

    st.write(
        "If the average of the y values is more accurate than the model's prediction, there will be no reason to use it.\n\n"
        "For this reason, the next thing I will do is to calculate the average of the y values and it's loss, I will later compare this value to the model's loss."
    )

    baseline_prediction = round(np.mean(y), 2)
    st.badge("Baseline predicition (always the same value): " + str(baseline_prediction), color="violet")
    baseline_loss = round(np.mean(np.abs(y - baseline_prediction)), 2)
    st.session_state.bl_loss = baseline_loss
    st.badge("Baseline loss: " + str(baseline_loss), color="violet")

    con, prev = st.columns(2)

    if con.button("Continue"):
        st.session_state.stage = 5
        st.rerun()
    if prev.button("Previous"):
        st.session_state.stage = 3
        st.rerun()

elif st.session_state.stage == 5:
    st.header("Creating the model")
    st.write("Now all that is left to do is to create the model, train it, and make sure that its loss is less than that of the baseline prediction.")

    x = st.session_state.x
    y = st.session_state.y

    x_reshaped = x.reshape(-1, 1)

    model = LinearRegression()
    model.fit(x_reshaped, y)

    st.success("Model was trained successfully")

    st.info("The w and b of the model:\n\nw: " + str(model.coef_[0]) + "\n\nb: " + str(model.intercept_))

    st.write("The last step is calculating its loss")

    y_hat = model.predict(x_reshaped)
    model_loss = np.mean(np.abs(y - y_hat))

    st.badge("Model loss: " + str(model_loss))
    st.success(
        "As seen from the calculation, the loss of our model is less than that of the baseline prediction:\n\n"
        "Baseline prediction loss: " + str(st.session_state.bl_loss) + "\n\n"
        "Model loss: " + str(round(model_loss, 2))
    )

    if st.button("Previous"):
        st.session_state.stage = 4
        st.rerun()

